theme = "6-colors"
# themes can be
# "catppuccin-mocha"
# "catppuccin-frappe"
# "catppuccin-latte"
# "catppuccin-macchiato"
# "grayscale"
# "classic"
# "high-intensity"
border = "white"
# border can be "white", "none","theme"
dot = ""
# dot can be any non whitespace string
disableColors = false
# to disable last line
fields = [
  "user",
  "shell",
  "pkgs",
  "host",
  "kernel",
  "uptime",
  "memory",
  "distro",
]
# these are all the available fields for now
