
# themes can be
# "catppuccin-mocha"
# "catppuccin-frappe"
# "catppuccin-latte"
# "catppuccin-macchiato"
# "grayscale"
# "classic"
# "high-intensity"
# "kanagawa-wave"
# "kanagawa-lotus"
# "kanagawa-dragon"
theme = "kanagawa-dragon"


# border can be "white", "none","theme"
border = "white"

# dot can be any non whitespace string
dot = "󰜪"

#disale the symbols line
disableColors = false

# to enable slow printing
slow = true

# to randomise th order of colors
random = false

# to print the fields and values in the same color
symmetric = true

# these are all the available fields
fields = [
  "user",
  "shell",
  "pkgs",
  "host",
  "kernel",
  "uptime",
  "memory",
  "distro",
  "de",
  "term",
]
